//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Idioma", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string EtiquetaIdiomaEsp {
            get {
                return ResourceManager.GetString("EtiquetaIdiomaEsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string EtiquetaIdiomaIng {
            get {
                return ResourceManager.GetString("EtiquetaIdiomaIng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Prospecto.
        /// </summary>
        internal static string lblAddProspect {
            get {
                return ResourceManager.GetString("lblAddProspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        internal static string lblApMaterno {
            get {
                return ResourceManager.GetString("lblApMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string lblApPaterno {
            get {
                return ResourceManager.GetString("lblApPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        internal static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal&lt;br/&gt;Técnico&amp;nbsp;.
        /// </summary>
        internal static string lblAuditores {
            get {
                return ResourceManager.GetString("lblAuditores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auditores.
        /// </summary>
        internal static string lblAuditoresLateral {
            get {
                return ResourceManager.GetString("lblAuditoresLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        internal static string lblCalle {
            get {
                return ResourceManager.GetString("lblCalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición (Cargo).
        /// </summary>
        internal static string lblCargo {
            get {
                return ResourceManager.GetString("lblCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificación.
        /// </summary>
        internal static string lblCertification {
            get {
                return ResourceManager.GetString("lblCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string lblCiudad {
            get {
                return ResourceManager.GetString("lblCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string lblClienteAct {
            get {
                return ResourceManager.GetString("lblClienteAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivo.
        /// </summary>
        internal static string lblClienteIna {
            get {
                return ResourceManager.GetString("lblClienteIna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Cliente.
        /// </summary>
        internal static string lblClientName {
            get {
                return ResourceManager.GetString("lblClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Postal.
        /// </summary>
        internal static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia.
        /// </summary>
        internal static string lblColonia {
            get {
                return ResourceManager.GetString("lblColonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competencias&lt;br/&gt;&amp;nbsp;.
        /// </summary>
        internal static string lblCompetencias {
            get {
                return ResourceManager.GetString("lblCompetencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competencias.
        /// </summary>
        internal static string lblCompetenciasLateral {
            get {
                return ResourceManager.GetString("lblCompetenciasLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto Principal.
        /// </summary>
        internal static string lblContPrincipal {
            get {
                return ResourceManager.GetString("lblContPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso.
        /// </summary>
        internal static string lblCourse {
            get {
                return ResourceManager.GetString("lblCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delagacion.
        /// </summary>
        internal static string lblDelegacion {
            get {
                return ResourceManager.GetString("lblDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción (Alcance).
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Fiscal.
        /// </summary>
        internal static string lblDirecFis {
            get {
                return ResourceManager.GetString("lblDirecFis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutivo de Ventas:.
        /// </summary>
        internal static string lblEjecutivoVentas {
            get {
                return ResourceManager.GetString("lblEjecutivoVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finanzas&lt;br/&gt;&amp;nbsp;.
        /// </summary>
        internal static string lblFinanzas {
            get {
                return ResourceManager.GetString("lblFinanzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finanzas.
        /// </summary>
        internal static string lblFinanzasLateral {
            get {
                return ResourceManager.GetString("lblFinanzasLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuente.
        /// </summary>
        internal static string lblFuente {
            get {
                return ResourceManager.GetString("lblFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio &lt;br/&gt;&amp;nbsp;.
        /// </summary>
        internal static string lblInicio {
            get {
                return ResourceManager.GetString("lblInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructor &lt;br/&gt;&amp;nbsp;.
        /// </summary>
        internal static string lblInstructor {
            get {
                return ResourceManager.GetString("lblInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructor.
        /// </summary>
        internal static string lblInstructorLateral {
            get {
                return ResourceManager.GetString("lblInstructorLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interesado en.
        /// </summary>
        internal static string lblinteres {
            get {
                return ResourceManager.GetString("lblinteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero Exterior.
        /// </summary>
        internal static string lblNumExterior {
            get {
                return ResourceManager.GetString("lblNumExterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero Interior.
        /// </summary>
        internal static string lblNumInterior {
            get {
                return ResourceManager.GetString("lblNumInterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais.
        /// </summary>
        internal static string lblPais {
            get {
                return ResourceManager.GetString("lblPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planeación y &lt;br/&gt;Logistica.
        /// </summary>
        internal static string lblPlaneacion {
            get {
                return ResourceManager.GetString("lblPlaneacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planeación y Logistica.
        /// </summary>
        internal static string lblPlaneacionLateral {
            get {
                return ResourceManager.GetString("lblPlaneacionLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string lblProspectAdd {
            get {
                return ResourceManager.GetString("lblProspectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar y Nuevo.
        /// </summary>
        internal static string lblProspectAddAndNew {
            get {
                return ResourceManager.GetString("lblProspectAddAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string lblProspectCancel {
            get {
                return ResourceManager.GetString("lblProspectCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social.
        /// </summary>
        internal static string lblRazon {
            get {
                return ResourceManager.GetString("lblRazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendado por.
        /// </summary>
        internal static string lblRecomendado {
            get {
                return ResourceManager.GetString("lblRecomendado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos  &lt;br/&gt;Humanos.
        /// </summary>
        internal static string lblRecursos {
            get {
                return ResourceManager.GetString("lblRecursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos Humanos.
        /// </summary>
        internal static string lblRecursosLateral {
            get {
                return ResourceManager.GetString("lblRecursosLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt;(Requerido)&lt;/strong&gt;.
        /// </summary>
        internal static string lblRequerido {
            get {
                return ResourceManager.GetString("lblRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC.
        /// </summary>
        internal static string lblRFC {
            get {
                return ResourceManager.GetString("lblRFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio al  &lt;br/&gt;Cliente.
        /// </summary>
        internal static string lblServicio {
            get {
                return ResourceManager.GetString("lblServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio al Cliente.
        /// </summary>
        internal static string lblServicioLateral {
            get {
                return ResourceManager.GetString("lblServicioLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estandard.
        /// </summary>
        internal static string lblStandard {
            get {
                return ResourceManager.GetString("lblStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas&lt;br/&gt;&amp;nbsp;.
        /// </summary>
        internal static string lblVentas {
            get {
                return ResourceManager.GetString("lblVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        internal static string lblVentasLateral {
            get {
                return ResourceManager.GetString("lblVentasLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitio Web.
        /// </summary>
        internal static string lblWeb {
            get {
                return ResourceManager.GetString("lblWeb", resourceCulture);
            }
        }
    }
}
